Create Procedure create_playfact

AS

Create table PlayFact
(
	PlayKey											int				not null	Identity(1,1)											,
	GameKey											int 			not null															,
	GameDateKey										int																					,
	YearID											smallint																			,
	EventNum										tinyint 		not null															,
	IsNewGame										bit 																				,
	IsEndOfGame										bit 																				,
	HomeTeamID										char(3) 																			,
	AwayTeamID										char(3) 																			,
	Inning											tinyint 																			,
	BattingTeam										bit 																				,
	OutsPrior										tinyint 																			,
	HomeScorePrior									tinyint 																			,
	AwayScorePrior									tinyint 																			,
	Balls											tinyint 																			,
	Strikes											tinyint 																			,
	BatterKey										int 						Foreign Key References Person(PersonKey)				,
	BatterHand										char(1) 																			,
	BatterDefensivePosition							tinyint 																			,
	BatterRemovedForPinchHitDefensivePosition		tinyint 																			,
	BatterLineupPosition							tinyint 																			,
	PitcherKey										int 						Foreign Key References Person(PersonKey)				,
	PitcherHand										char(1)																				,
	CatcherKey										int 						Foreign Key References Person(PersonKey)				,
	FirstBasemanKey									int 						Foreign Key References Person(PersonKey)				,
	SecondBasemanKey								int 						Foreign Key References Person(PersonKey)				,
	ThirdBasemanKey									int 						Foreign Key References Person(PersonKey)				,
	ShortstopKey									int 						Foreign Key References Person(PersonKey)				,
	LeftFielderKey									int 						Foreign Key References Person(PersonKey)				,
	CenterFielderKey								int 						Foreign Key References Person(PersonKey)				,
	RightFielderKey									int 						Foreign Key References Person(PersonKey)				,
	FirstRunnerKey									int 						Foreign Key References Person(PersonKey)				,
	SecondRunnerKey									int 						Foreign Key References Person(PersonKey)				,
	ThirdRunnerKey									int 						Foreign Key References Person(PersonKey)				,
	ResponsiblePitcherFirstKey						int 						Foreign Key References Person(PersonKey)				,
	ResponsiblePitcherSecondKey						int 						Foreign Key References Person(PersonKey)				,
	ResponsiblePitcherThirdKey						int 						Foreign Key References Person(PersonKey)				,
	IsPinchHit										bit 																				,
	BatterRemovedForPinchHitKey						int 						Foreign Key References Person(PersonKey)				,
	IsPinchRunnerOn1st								bit 																				,
	RunnerRemovedForPinchRunnerOn1stKey				int 						Foreign Key References Person(PersonKey)				,
	IsPinchRunnerOn2nd								bit 																				,
	RunnerRemovedForPinchRunnerOn2ndKey				int 						Foreign Key References Person(PersonKey)				,
	IsPinchRunnerOn3rd								bit 																				,
	RunnerRemovedForPinchRunnerOn3rdKey				int 						Foreign Key References Person(PersonKey)				,
	IsLeadoff										bit 																				,
	EventTypeKey									int		 																			,
	IsBatterEvent									bit 																				,
	IsAB											bit 																				,
	TotalBases										tinyint 																			,
	IsSacrifice										bit 																				,
	OutsOnPlay										tinyint 																			,
	OutsAfter										tinyint																				,
	RBIOnPlay										tinyint 																			,
	RunnerOn1stDest									tinyint																				,
	RunnerOn2ndDest									tinyint																				,
	RunnerOn3rdDest									tinyint																				,
	BatterDest										tinyint																				,
	RunsOnPlay										tinyint																				,
	HomeScoreAfter									tinyint																				,
	AwayScoreAfter									tinyint																				,
	IsPassedBall									bit 																				,
	IsWildPitch										bit 																				,
	FieldedBy										tinyint 																			,
	BattedBallType									char(1) 																			,
	IsBunt											bit 																				,
	IsFoul											bit 																				,
	FirstPOFielderKey								int 						Foreign Key References Person(PersonKey)				,
	FirstPOFielderPosition							tinyint 																			,
	SecondPOFielderKey								int 						Foreign Key References Person(PersonKey)				,
	SecondPOFielderPosition							tinyint 																			,
	ThirdPOFielderKey								int 						Foreign Key References Person(PersonKey)				,
	ThirdPOFielderPosition							tinyint 																			,
	FirstAssistFielderKey							int 						Foreign Key References Person(PersonKey)				,
	FirstAssistFielderPosition						tinyint 																			,
	SecondAssistFielderKey							int 						Foreign Key References Person(PersonKey)				,
	SecondAssistFielderPosition						tinyint 																			,
	ThirdAssistFielderKey							int 						Foreign Key References Person(PersonKey)				,
	ThirdAssistFielderPosition						tinyint 																			,
	FourthAssistFielderKey							int 						Foreign Key References Person(PersonKey)				,
	FourthAssistFielderPosition						tinyint 																			,
	FifthAssistFielderKey							int 						Foreign Key References Person(PersonKey)				,
	FifthAssistFielderPosition						tinyint 																			,
	NumErrors										tinyint 																			,
	FirstErrorPlayerKey								int 						Foreign Key References Person(PersonKey)				,
	FirstErrorPlayerPosition						tinyint 																			,
	FirstErrorType									char(1) 																			,
	SecondErrorPlayerKey							int 						Foreign Key References Person(PersonKey)				,
	SecondErrorPlayerPosition						tinyint 																			,
	SecondErrorType									char(1) 																			,
	ThirdErrorPlayerKey								int 						Foreign Key References Person(PersonKey)				,
	ThirdErrorPlayerPosition						tinyint 																			,
	ThirdErrorType									char(1) 																				,
	IsSBRunnerOn1st									bit 																				,
	IsSBRunnerOn2nd								    bit																					,
	IsSBRunnerOn3rd								    bit																					,
	IsCSRunnerOn1st								    bit																					,
	IsCSRunnerOn2nd								    bit																					,
	IsCSRunnerOn3rd								    bit																					,
	IsPORunnerOn1st								    bit																					,
	IsPORunnerOn2nd								    bit																					,
	IsPORunnerOn3rd								    bit																					,
	IsUnmappedNonBatterEvent					    bit																					,
	Primary Key (PlayKey, GameKey, EventNum)																							,
	Constraint Unique_GameEvent Unique (GameKey, EventNum)
)

GO